[output]
name = "sbcl build"
output_command = "cd sbcl && git reset --hard > /dev/null && sh make.sh 'clisp'"
output_buffer = "100k" # how much initial data to capture

[sox]
bit_depth = 8
sample_rate = 11000
channels = 1
encoding = "unsigned"
#other_options = "" # optional

# optional
[build]
#always_rebuild = true # optional
build_command = ""
http_sources = []
git_sources = [
            "https://github.com/sbcl/sbcl"
]
