[output]
name = "cat vmlinuz-linux"
output_command = "cat /boot/vmlinuz-linux"
output_buffer = "10M"

[sox]
bit_depth = 8
sample_rate = 16575
channels = 2
encoding = "unsigned"
tempo = 0.20
other_options_post = "-r 44100"

[[clip]]
start = "0:0:00"
end = "0:3:40"
position = "relative"