[output]
name = "ls -R /"
output_command = "ls -R /"
output_buffer = "5M" # how much initial data to capture

[sox]
bit_depth = 8
sample_rate = 44000
channels = 2
encoding = "unsigned"
#other_options = "" # optional

[[clip]]
start = "0:00:03" # %T format
end = "0:0:05" # end is absolute too!
position = "absolute"

[[clip]]
start = "0:00:10" # %T format
end = "0:0:12" # end is relative too!
position = "absolute"