[output]
name = "ls -R /"
output_command = "ls -R /"
output_buffer = "5M" # how much initial data to capture

[sox]
bit_depth = 8
sample_rate = 44000
channels = 2
encoding = "unsigned"
#other_options = "" # optional

# optional
[build]
build_command = "ree"
http-sources = [
        "",
]
git-sources = [
        "",
]
