[output]
name = "ls -R"
output_command = "ls -R /"
output_buffer = "75M"

[sox]
bit_depth = 8
sample_rate = 44000
channels = 2
encoding = "unsigned"
#other_options = "" # optional
tempo = 1.0 # optional, defaults to 1.0

[[clip]]
start = "0:00:00"
end = "0:01:20"
position = "absolute"

[[clip]]
start = "0:02:00"
end = "0:01:40" # 3:00
position = "relative"

[[clip]]
start = "0:02:30"
end = "0:01:30" # 4:30
position = "relative"

[[clip]]
start = "0:04:30"
end = "0:00:50"
position = "relative"