[track]
name = "ls -R /"
# build_command = "" # not required here
output_command = "ls -R /"
output_buffer = "1M" # how much initial data to capture

[sox]
bit_depth = 8
sample_rate = 44000
channels = 2
encoding = "unsigned"
#other_options = "" # optional