[package]
name = "sotclk"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
toml = "^0.5.0"
serde = { version = "^1.0.0", features = ["derive"]}
curl = "^0.4.0"
chrono = "^0.4"