[output]
name = "kernelbuild"
output_command = "cd linux-5.10 && make clean && strace -f make 2>&1" # redirect for warnings
output_buffer = "200M"

[sox]
bit_depth = 8
sample_rate = 44100
channels = 2
encoding = "unsigned"

[build]
build_command = "tar -xvf v5.10 && cd linux-5.10 && make defconfig"
http_sources = ["https://codeload.github.com/torvalds/linux/tar.gz/v5.10"]
git_sources = []
copy_me = false

[[clip]]
start = "0:01:20"
end = "0:00:35"
position = "relative"

[[clip]]
start = "0:02:10"
end = "0:00:35"
position = "relative"

[[clip]]
start = "0:02:10"
end = "0:00:8"
position = "relative"

[[clip]]
start = "0:00:20"
end = "0:01:10" # 2:18
position = "relative"

[[clip]]
start = "0:01:16"
end = "0:01:26" # 3:54
position = "relative"

[[clip]]
start = "0:15:00"
end = "0:00:20" # 4:14
position = "relative"

[[clip]]
start = "0:07:30"
end = "0:00:48"
position = "relative"