[output]
name = "classroom.blend"
output_command = "cat classroom/classroom.blend"
output_buffer = "50M" # how much initial data to capture
#debug = true # option, false by default
#cache = true # option, true by default

[sox]
bit_depth = 8
sample_rate = 22100
channels = 2
encoding = "unsigned"
other_options_post = "-r 44100"
#other_options = "" # optional
tempo = 1.0

# optional
[build]
#always_rebuild = true # optional
build_command = "unzip -u classroom.zip"
http_sources = [
        "https://download.blender.org/demo/test/classroom.zip",
]
git_sources = []
copy_me = false


[[clip]]
start = "0:00:00"
end = "0:01:18"
position = "absolute"

[[clip]]
start = "0:08:42"
end = "0:10:00"
position = "absolute" # runs out of data but I'm not fixing how it's clipped