[output]
name = "classroom.blend"
output_command = "cat classroom/classroom.blend"
output_buffer = "1M" # how much initial data to capture
#debug = true # option, false by default
cache = true # option, true by default

[sox]
bit_depth = 8
sample_rate = 44000
channels = 2
encoding = "unsigned"
#other_options = "" # optional

# optional
[build]
build_command = "unzip -u classroom.zip"
http_sources = [
        "https://download.blender.org/demo/test/classroom.zip",
]
git_sources = [
            "https://github.com/Shizcow/SOTCLK.git", # just for testing
]
