[output]
name = "find Android SDK | xargs cat"
output_command = "find ~/Android/Sdk/ | xargs cat"
output_buffer = "20M" # how much initial data to capture

[sox]
bit_depth = 8
sample_rate = 22000
channels = 1
encoding = "unsigned"
other_options_post = "-r 44100"
#other_options = "" # optional
tempo = 0.5 # optional, defaults to 1.0

[[clip]]
start = "0:00:30"
end = "0:02:30"
position = "absolute"

[[clip]]
start = "0:00:30"
end = "0:00:30" # 2:30
position = "relative"

[[clip]]
start = "0:06:20"
end = "0:00:04" # 3:33
position = "relative"

[[clip]]
start = "0:10:42"
end = "0:00:15"
position = "relative"