[album]
title = "Sounds of the Compiling Linux Kernal: Vol. 1 Remastered"
tracks = [
       "kernelbuild",
       "vmlinuz-linux",
       "sbcl",
       "ls",
       "rg",
       "journal",
       "android_sdk",
       "classroom",
       "tensorflow",
       "dotemacs",
]